[tool.ruff]
indent-width = 4
line-length = 80
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "E4",
    "E501",
    "F401",
    "F402",
    "F403",
    "F404",
    "F405",
    "F406",
    "UP010",
    "UP026",
    "UP029",
    "UP035"
]
select = ["E", "F", "UP"]

[tool.ruff.format]
indent-style = "space"
